### PR TITLE
[hotfix-1097] 修复数据库字段为null时，同步空指针问题

### LINKED ISSUE #1097: [Bug] [chunjun-connection] 数据库字段为null时，同步空指针
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar issues.

### What happened

当source为doris表，有如下一下记录时
```sql
INSERT INTO `` VALUES (2, 202231, 176, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 198009.3600, 37780.8500, NULL, 738305.4300, 499126.9500, 4511, 948, NULL, 13017, 9824, 3.2094, 43.8948, 39.8532, NULL, 56.7186, 50.8069, '2022-07-28 06:02:20');
```
doris -> mysql 会空指针 
image

### What you expected to happen

可能是在数据类型转换的时候，没有做空值处理

### How to reproduce

上面有建表语句，可以直接运行

### Anything else

_No response_

### Version

master

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by KinoMin**
## Which issue you fix
Fixes #1097.

## Checklist:

- [x] I have executed the **'mvn spotless:apply'** command to format my code.
- [x] I have a meaningful commit message (including the issue id, **the template of commit message is '[label-type-#issue-id][fixed-module] a meaningful commit message.'**)
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have checked my code and corrected any misspellings.
- [ ] My commit is only one. (If there are multiple commits, you can use 'git squash' to compress multiple commits into one.)

### CODE REVIEW

**Comment by ll076110** [comment]
Could you try the val.isNullAt (int pos) method?

**Comment by KinoMin** [comment]
> Could you try the val.isNullAt (int pos) method?

It has been modified.

File: chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/converter/JdbcColumnConverter.java [hunk 1]
```diff
@@ -30,6 +30,7 @@
 import com.dtstack.chunjun.element.column.BigDecimalColumn;
 import com.dtstack.chunjun.element.column.BooleanColumn;
 import com.dtstack.chunjun.element.column.BytesColumn;
+import com.dtstack.chunjun.element.column.NullColumn;
```
Comment (FlechazoW) [inline chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/converter/JdbcColumnConverter.java:33]: This is a useless imports.
